const sampleWheels = [
  {
    cycleId: "WHEEL001",
    modelName: "Hero Sprint Pro",
    type: "Mountain Bike",
    rentPrice: 150,
    availabilityStatus: "Available",
    currentLocation: "Sector 10, Downtown",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/84.jpg",
    condition: "Excellent",
    accessories: "Helmet, Lock",
    addedDate: new Date(),
    usageHistory: 0,
  },
  {
    cycleId: "WHEEL002",
    modelName: "Firefox Fusion",
    type: "Road Bike",
    rentPrice: 120,
    availabilityStatus: "Rented",
    currentLocation: "Main Street, City Center",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/83.jpg",
    condition: "Good",
    accessories: "Basket, Lock",
    addedDate: new Date(),
    usageHistory: 2,
  },
  {
    cycleId: "WHEEL003",
    modelName: "Btwin MyBike",
    type: "Hybrid Bike",
    rentPrice: 100,
    availabilityStatus: "Available",
    currentLocation: "Sector 21, Park Area",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/82.jpg",
    condition: "Fair",
    accessories: "Helmet",
    addedDate: new Date(),
    usageHistory: 1,
  },
  {
    cycleId: "WHEEL004",
    modelName: "UrbanTrail Zinger",
    type: "Mountain Bike",
    rentPrice: 140,
    availabilityStatus: "Available",
    currentLocation: "Sector 15, Lakeview",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/81.jpg",
    condition: "Excellent",
    accessories: "Helmet, Lock",
    addedDate: new Date(),
    usageHistory: 4,
  },
  {
    cycleId: "WHEEL005",
    modelName: "Montra Helicon Disc",
    type: "Road Bike",
    rentPrice: 180,
    availabilityStatus: "Rented",
    currentLocation: "Market Square",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/80.jpg",
    condition: "Good",
    accessories: "Lock",
    addedDate: new Date(),
    usageHistory: 3,
  },
  {
    cycleId: "WHEEL006",
    modelName: "Mach City iBike",
    type: "Hybrid Bike",
    rentPrice: 90,
    availabilityStatus: "Available",
    currentLocation: "Central Park",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/79.jpg",
    condition: "Fair",
    accessories: "Basket",
    addedDate: new Date(),
    usageHistory: 0,
  },
  {
    cycleId: "WHEEL007",
    modelName: "Hercules Roadeo",
    type: "Mountain Bike",
    rentPrice: 160,
    availabilityStatus: "Available",
    currentLocation: "Sector 9, Tech Park",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/78.jpg",
    condition: "Good",
    accessories: "Helmet, Lock",
    addedDate: new Date(),
    usageHistory: 5,
  },
  {
    cycleId: "WHEEL008",
    modelName: "La Sovereign Dynamite",
    type: "Road Bike",
    rentPrice: 175,
    availabilityStatus: "Rented",
    currentLocation: "Sector 5, Residential Area",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/77.jpg",
    condition: "Good",
    accessories: "Lock",
    addedDate: new Date(),
    usageHistory: 3,
  },
  {
    cycleId: "WHEEL009",
    modelName: "Trek FX 2",
    type: "Hybrid Bike",
    rentPrice: 130,
    availabilityStatus: "Available",
    currentLocation: "University Campus",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/76.jpg",
    condition: "Excellent",
    accessories: "Helmet, Lock, Basket",
    addedDate: new Date(),
    usageHistory: 2,
  },
  {
    cycleId: "WHEEL010",
    modelName: "Giant Escape 3",
    type: "Road Bike",
    rentPrice: 155,
    availabilityStatus: "Available",
    currentLocation: "Sector 12, Mall Road",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/75.jpg",
    condition: "Excellent",
    accessories: "Helmet",
    addedDate: new Date(),
    usageHistory: 4,
  },
  {
    cycleId: "WHEEL011",
    modelName: "Btwin Riverside 500",
    type: "Hybrid Bike",
    rentPrice: 125,
    availabilityStatus: "Rented",
    currentLocation: "Business District",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/73.jpg",
    condition: "Good",
    accessories: "Basket",
    addedDate: new Date(),
    usageHistory: 3,
  },
  {
    cycleId: "WHEEL012",
    modelName: "Schwinn Frontier",
    type: "Mountain Bike",
    rentPrice: 170,
    availabilityStatus: "Available",
    currentLocation: "Sector 4, Sports Complex",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/72.jpg",
    condition: "Excellent",
    accessories: "Helmet, Lock",
    addedDate: new Date(),
    usageHistory: 1,
  },
  {
    cycleId: "WHEEL013",
    modelName: "Fantom Bike",
    type: "Mountain Bike",
    rentPrice: 160,
    availabilityStatus: "Rented",
    currentLocation: "Sector 7, Corporate Plaza",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/70.jpg",
    condition: "Good",
    accessories: "Helmet, Lock",
    addedDate: new Date(),
    usageHistory: 5,
  },
  {
    cycleId: "WHEEL014",
    modelName: "Polygon Cascade 4",
    type: "Hybrid Bike",
    rentPrice: 145,
    availabilityStatus: "Available",
    currentLocation: "Sector 18, Tech City",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/66.jpg",
    condition: "Excellent",
    accessories: "Helmet",
    addedDate: new Date(),
    usageHistory: 2,
  },
  {
    cycleId: "WHEEL015",
    modelName: "Riverside 900",
    type: "Road Bike",
    rentPrice: 10,
    availabilityStatus: "Available",
    currentLocation: "Sector 16, Business Center",
    image: "https://d3dbysmy5y25ht.cloudfront.net/wallpaper/mobile/66.jpg",
    condition: "Fair",
    accessories: "Basket, Lock",
    addedDate: new Date(),
    usageHistory: 1,
  },
];

module.exports = { data: sampleWheels };
